impactMarket/mobile-app

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/views/community/details/index.tsx
(review and choose "rebase and merge" option to merge)
> copy community description to clipboard

- src/components/Modal.tsx
- src/helpers/types/models.ts
- src/services/api/routes/community.ts
- src/views/community/manager/index.tsx
Linked to https://github.com/impactMarket/api/pull/11
> request change ubi params

- package.json
- src/helpers/index.ts
- src/services/api/routes/user.ts
- yarn.lock
Linked to https://github.com/impactMarket/api/pull/13
phone and ip are hashed.
> device identification

- src/services/api/routes/user.ts
- src/views/profile/index.tsx
related to https://github.com/impactMarket/api/pull/25
> do not send address on request

- package.json
- yarn.lock
tentatively solving
```
java.lang.RuntimeException: Expo encountered a fatal error: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), stack:
exports@28:433
value@43:3215
<unknown>@43:747
value@43:2610
value@43:719
value@-1
at host.exp.exponent.experience.q.E(BaseExperienceActivity.java
at host.exp.exponent.experience.-$$Lambda$BaseExperienceActivity$zZZNiLUhJmY4AlwF2loJATXcbqc.run (-.java:2)
at android.os.Handler.handleCallback (Handler.java:883)
at android.os.Handler.dispatchMessage (Handler.java:100)
at android.os.Looper.loop (Looper.java:214)
at android.app.ActivityThread.main (ActivityThread.java:7438)
at java.lang.reflect.Method.invoke (Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run …
```
> add react-native to resolutions package.json

- src/services/celoWallet.ts
- src/services/pushNotifications/index.ts
- src/views/community/beneficiary/Claim.tsx
- src/views/community/manager/views/AddBeneficiaryScreen.tsx
- src/views/community/manager/views/AddManagerScreen.tsx
- src/views/community/manager/views/AddedBeneficiaryScreen.tsx
- src/views/community/manager/views/AddedManagerScreen.tsx
- src/views/profile/auth/index.tsx
Possibly fixing `h.t0.toLowerCase is not a function. (In 'h.t0.toLowerCase()', 'h.t0.toLowerCase' is undefined)`
> fix tolowercase not function

- src/services/api/routes/community.ts
I change the endpoint name to /create and add /add again for backward compatibility
> update endpoint to create community

- .circleci/config.yml
migrated from https://github.com/impactMarket/mobile-app/pull/28
> new ci config

- src/views/community/beneficiary/AnonymousReportScreen.tsx
This PR fixes the input field on Anonymous Report Screen, changing it from a normal input to a multi-line one.
> add missing prop to AnonymousReportScreen field

- src/views/stories/Container.tsx
This PR reorganizes inner elements from the Carrousel component in order to fix header misplace.
> add repositioning from inner elements

- src/components/BaseCommunity.tsx
- src/helpers/index.ts
- src/navigator/header/CreateCommunity.tsx
- src/services/api/base.ts
- src/services/api/routes/community.ts
- src/services/api/routes/story.ts
- src/services/api/routes/system.ts
- src/services/api/routes/user.ts
- src/views/communities/Stories.tsx
- src/views/createCommunity/index.tsx
- src/views/stories/CarouselSlide.tsx
- src/views/stories/index.tsx
* use thumbnails more often for faster loading
* add loading icon while story image is loading
* load just 5 more recent stories on community page
* change API routes result for "get" and "post" to support count and error, respectively
* hide create button for non-logged users
* copy error to clipboard if create community fails
> final improvments

- src/views/communities/StoriesCard.tsx
- src/views/stories/StoriesCarousel.tsx
- src/views/stories/index.tsx
https://user-images.githubusercontent.com/44679989/120799826-20da9080-c537-11eb-8057-fa02ccc26358.mp4
> add onScrollToIndexFailed handler

- src/views/community/details/index.tsx
- Updates token_transfers with token-transfers value in order to reflect the change made by CELO team.
> replace token_transfers w/ token-transfers

- src/views/createCommunity/index.tsx
This PR fixes [IPCT1-246] at https://impactmarket.atlassian.net/browse/IPCT1-246
**Changes**
Decrease size of modals on CreateCommunity flow.
Decrease spacing between elements within modals
> fix modal size to fit multiple devices

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/views/createCommunity/index.tsx
- src/views/profile/index.tsx
This Pull request implements[IPCT1-192] of https://impactmarket.atlassian.net/browse/IPCT1-192
> add func to check image dimensions

- src/navigator/header/CreateCommunity.tsx
This Pull Request implements [IPCT1-244] of https://impactmarket.atlassian.net/browse/IPCT1-244
https://user-images.githubusercontent.com/44679989/122642626-45bc2f80-d103-11eb-97ea-47f8281a13fe.mp4
> add authentication protection on create community

- src/views/createCommunity/index.tsx
- src/views/profile/index.tsx
This PR Reverts size limit to min dimensions requirements instead of maximum dimensions requirements.
> add min size requirements on file upload

- App.tsx
- src/views/communities/Stories.tsx
- src/views/communities/StoriesCard.tsx
- src/views/createCommunity/index.tsx
- src/views/profile/index.tsx
- src/views/stories/index.tsx
IPCT1-287 - Fix stories card spacing and size adaptation based on devices size.
> [IPCT1-287, IPCT1-288, IPCT1-289, IPCT1-290] - Multiple fixes.

- index.d.ts
- package.json
- src/services/api/base.ts
- src/services/api/index.ts
- src/services/api/routes/community.ts
- src/services/api/routes/story.ts
- src/services/api/routes/user.ts
- src/views/createCommunity/index.tsx
- src/views/profile/index.tsx
- src/views/stories/NewStory.tsx
- yarn.lock
This relates to https://github.com/impactMarket/api/pull/63
result video [jump to 1:08 to start] https://drive.google.com/file/d/1IfvdxF4JoE7I7QwEUBHpAYDL8n5zMXYD/view?usp=sharing
note: the video was recorded on the low-end SLIDE device. Which crashed at first.
No new tests. Previous tests were broken on master.
> [IPCT1-281] update image uploading to use presigned url

- src/helpers/types/models.ts
- src/services/api/routes/community.ts
no UI changes. Endpoints work as expected.
Manually tested in staging and prod.
> split community endpoint

- src/views/communities/StoriesCard.tsx
- src/views/communities/index.tsx
- src/views/stories/index.tsx
This PR changes FlatList behaviour to improve performance.
> changes flatlist behavior and adj stories

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
Community pending view had a message with "X days".
just text fixes
just text fixes
just text fixes
> fix x days translations

- package.json
- yarn.lock
After `expo start` a message was presented, requiring changes in two dependencies. Plus, typescript version was wrong. An issue after sdk42 update, I think.
updates dependencies
manually
> adjust dependencies

- src/assets/countries.json
- src/helpers/index.ts
- src/views/createCommunity/index.tsx
- src/views/profile/auth/index.tsx
Sorry, this should have been included in https://github.com/impactMarket/mobile-app/pull/134
> finish #134

- App.tsx
- src/helpers/index.ts
- src/helpers/types/endpoints.ts
- src/services/api/routes/user.ts
- src/services/cacheStore.ts
- src/services/pushNotifications/index.ts
- src/views/profile/auth/index.tsx
- src/views/profile/index.tsx
To update accordingly with future endpoint standards, community object and exchange rates object are not returned in /auth either /welcome endpoints (currently they still are for backward purpose)
Fixes # (part of https://github.com/impactMarket/api/pull/67)
**Test Configuration**:
* Hardware: Asus Zenfone Max3
* SDK: Android 7
No UI/UX changes
> update IUserBaseAuth and IUserHello

- src/views/community/beneficiary/Claim.tsx
- src/views/community/beneficiary/index.tsx
This fixes the issue with claim locations. Both when not requested or not available.
Fixes IPCT1-249
**Test Configuration**:
* Device: Asus Zenfone Max 3
first test
https://drive.google.com/file/d/1GQwjFg3IBWZnLkhqgsSkHLaB75PFRvYN/view?usp=sharing
claim with GPS active but not allowed access
https://drive.google.com/file/d/1EePGnUfs9AiekvUz9r5h8Gpbaog0-mbt/view?usp=sharing
> [IPCT1-249] fix claim location permissions

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/helpers/redux/sagas/index.ts
- src/helpers/redux/sagas/offline.ts
This PR fixes [IPCT1-332] at https://impactmarket.atlassian.net/browse/IPCT1-332
This PR adds a connection strength awareness in order to inform users when their network is under a minimal performance/speed.
> [IPCT1-332] fix connection weakness

- src/components/core/HeaderBottomSheetTitle.tsx
- src/navigator/header/CreateCommunity.tsx
- src/views/createCommunity/index.tsx
This PR fixes [IPCT1-282] at https://impactmarket.atlassian.net/browse/IPCT1-282
This PR implements flex approach on createCommunity modals in order to allow the modal be responsive to all devices.
> [IPCT1-282] fix create community modal refactor

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/components/svg/header/BackSvg.tsx
- src/views/createCommunity/index.tsx
This PR fixes [IPCT1-280] at https://impactmarket.atlassian.net/browse/IPCT1-280
This PR adds a new modal to inform users about lost of inputs if they go back from create community without submitting.
> [IPCT1-280] add modals adjustments and close conditional

- .github/PULL_REQUEST_TEMPLATE.md
> include iPhone 6 in manual test device

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/views/communities/Stories.tsx
- src/views/community/beneficiary/Claim.tsx
- src/views/community/beneficiary/ClaimExplainedScreen.tsx
- src/views/community/beneficiary/index.tsx
- src/views/community/details/donate/modals/confirm.tsx
- src/views/createCommunity/index.tsx
This PR fixes [IPCT1-326] at https://impactmarket.atlassian.net/browse/IPCT1-326
This PR includes a new feedback to the user when his community is out of funds.
> [IPCT1-326] fix claim no funds warning

- package.json
- src/components/core/ModalValoraTimeoutError.tsx
- src/services/celoWallet.ts
- src/views/community/details/donate/modals/donate.tsx
- src/views/community/details/index.tsx
- src/views/createCommunity/index.tsx
- src/views/stories/Container.tsx
- yarn.lock
This PR fixes [IPCT1-360] at https://impactmarket.atlassian.net/browse/IPCT1-360
This PR fix an open bug in expo clipboard which we noticed on donate button but could happen in all clipboard usage. 
- [] [iPhone 6](https://www.gsmarena.com/apple_iphone_6-6378.php)
https://user-images.githubusercontent.com/44679989/128504722-d1366fbe-7c4b-4d04-88a3-79e946ab094c.MP4
> Fix/ipct1 360/fix copy contract bug

- App.tsx
> fix analytics setUserProperties

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/views/createEditCommunity/__tests__/create.test.tsx
- src/views/createEditCommunity/__tests__/snapshots.spec.tsx
- src/views/createEditCommunity/create.tsx
- src/views/createEditCommunity/metadata.tsx
- src/views/createEditCommunity/state.ts
This PR fixes [IPCT1-406] at https://impactmarket.atlassian.net/browse/IPCT1-406
With the refactoring of "create community", the option for a user to upload a profile picture was removed. This PR adds that feature back.
Same as it was before.
> [IPCT1-406] upload profile picture

- App.tsx
- package.json
- patches/react-native-modalize+2.0.8.patch
- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/helpers/redux/actions/auth.ts
- src/helpers/redux/reducers/auth.ts
- src/helpers/redux/sagas/auth.ts
- src/helpers/redux/sagas/index.ts
- src/helpers/types/redux.ts
- src/helpers/types/state.ts
- src/services/api/base.ts
- src/services/api/routes/user.ts
- src/views/profile/auth/index.tsx
This PR fixes [IPCT1-404] at https://impactmarket.atlassian.net/browse/IPCT1-404
This PR adds functionality to migrate accounts. It also fixes the modalize size/scroll.
migrate account
https://drive.google.com/file/d/1MMK3yibRG5tEAnMWqp1e7nifwcrg5RYK/view?usp=sharing
modalize fixed
https://drive.google.com/file/d/14lTeSqSTz-knR53VKo3gBb00dnLWgJFh/view?usp=sharing
> [IPCT1-404] migrate account

- src/views/community/beneficiary/Claim.tsx
This PR fixes [IPCT1-408] at https://impactmarket.atlassian.net/browse/IPCT1-408
It looks like there are issues getting the location at first. The issue has been reported by others and seems to be an issue with the latest versions. Not an ideal solution but the best one between losing data and downgrade to the previous SDK version. 
No UI changes
> [IPCT1-408] fix throw location

- src/views/community/beneficiary/Claim.tsx
- src/views/createEditCommunity/__tests__/__snapshots__/snapshots.spec.tsx.snap
This PR fixes [IPCT1-154] at https://impactmarket.atlassian.net/browse/IPCT1-154
See after and before videos.
after
https://drive.google.com/file/d/1zSiBkQ7poPIAvGk8vyoX3o8vx3loY035/view?usp=sharing
before
https://drive.google.com/file/d/1b53BDxWyMufqAGPRNwk3GZvSdGARmMlA/view?usp=sharing
> [IPCT1-154] fix beneficiary splash

- src/views/createEditCommunity/__tests__/__snapshots__/snapshots.spec.tsx.snap
- src/views/createEditCommunity/create.tsx
- src/views/createEditCommunity/state.ts
No issue linked.
The verification modal was removed by mistake when refactoring the create community view. THis PR adds it back.
https://drive.google.com/file/d/1IHYo6hR9uQVQXd9SnCJ1D3Oi54UiN5QY/view?usp=sharing
> Add back prevent go back create community

- App.tsx
- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/components/CommunityStatus.tsx
- src/components/core/ModalValoraTimeoutError.tsx
- src/helpers/index.ts
- src/views/communities/index.tsx
- src/views/community/beneficiary/Claim.tsx
- src/views/community/beneficiary/index.tsx
- src/views/community/manager/cards/Beneficiaries.tsx
- src/views/community/manager/index.tsx
- src/views/community/manager/views/AddBeneficiaryScreen.tsx
- src/views/community/manager/views/AddManagerScreen.tsx
- src/views/community/manager/views/AddedBeneficiaryScreen.tsx
- src/views/community/manager/views/AddedManagerScreen.tsx
- src/views/community/manager/views/ScanQR.tsx
- src/views/createEditCommunity/__tests__/create.test.tsx
- src/views/createEditCommunity/create.tsx
- src/views/createEditCommunity/edit.tsx
- src/views/createEditCommunity/metadata.tsx
- src/views/profile/auth/index.tsx
- src/views/profile/index.tsx
- src/views/stories/Container.tsx
- src/views/stories/NewStory.tsx
No issue linked. Another review of translations.
> another translations review

- .circleci/config.yml
No issue linked.
Changes resource class circleci so we get the deploy to work on every merge as intended.
> change resource class circleci

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/components/Divider.tsx
- src/components/Modal.tsx
- src/components/svg/CloseSvg.tsx
- src/helpers/constants.ts
- src/helpers/index.ts
- src/helpers/redux/actions/auth.ts
- src/helpers/redux/reducers/auth.ts
- src/helpers/redux/sagas/auth.ts
- src/helpers/types/redux.ts
- src/navigator/header/Logout.tsx
- src/services/api/base.ts
- src/services/api/routes/story.ts
- src/services/api/routes/user.ts
- src/views/community/extendedDetails/index.tsx
- src/views/profile/auth/index.tsx
- src/views/profile/index.tsx
This PR fixes [IPCT1-369] at https://impactmarket.atlassian.net/browse/IPCT1-369
> [IPCT1-369] User delete account

- src/services/api/base.ts
- src/services/api/routes/community.ts
- src/services/api/routes/user.ts
- src/views/createEditCommunity/__tests__/create.test.tsx
- src/views/createEditCommunity/create.tsx
- src/views/createEditCommunity/edit.tsx
- src/views/profile/index.tsx
This PR fixes [IPCT1-431] at https://impactmarket.atlassian.net/browse/IPCT1-431
> [IPCT1-431] refactor image upload

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/components/Modal.tsx
- src/components/core/Select.tsx
- src/views/createEditCommunity/__tests__/__snapshots__/snapshots.spec.tsx.snap
- src/views/createEditCommunity/__tests__/create.test.tsx
- src/views/createEditCommunity/contract.tsx
- src/views/createEditCommunity/create.tsx
- src/views/createEditCommunity/state.ts
This PR fixes [IPCT1-425] at https://impactmarket.atlassian.net/browse/IPCT1-425
- This change requires a documentation update
> [IPCT1-425] no default dropdown community creation

- package.json
- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/views/createEditCommunity/InfoIcon.tsx
- src/views/createEditCommunity/__tests__/__snapshots__/snapshots.spec.tsx.snap
- src/views/createEditCommunity/create.tsx
This PR fixes [IPCT1-444] at https://impactmarket.atlassian.net/browse/IPCT1-444
- Manually
- Automated
> [IPCT1-444] Disclaimer create community

- src/components/ShimmerPlaceholder.tsx
- src/views/createEditCommunity/metadata.tsx
This PR fixes [IPCT1-435] at https://impactmarket.atlassian.net/browse/IPCT1-435
- Manually
- Automated
> [IPCT1-435] shimmer effect edit community

- src/styles/index.ts
- src/views/community/manager/index.tsx
This PR fixes [IPCT1-434] at https://impactmarket.atlassian.net/browse/IPCT1-434
- Manually
- Automated
> [IPCT1-434] add manager rules in pending screen

- src/views/createEditCommunity/contract.tsx
- src/views/createEditCommunity/create.tsx
- src/views/createEditCommunity/metadata.tsx
This PR fixes [IPCT1-439] at https://impactmarket.atlassian.net/browse/IPCT1-439
- Manually
- Automated
> [IPCT1-439] abort community submission

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/components/Modal.tsx
- src/services/cacheStore.ts
- src/views/createEditCommunity/__tests__/create.test.tsx
- src/views/createEditCommunity/create.tsx
This PR fixes [IPCT1-416] at https://impactmarket.atlassian.net/browse/IPCT1-416
- Manually
- Automated
> [IPCT1-416] save community details locally

- src/views/community/manager/views/AddBeneficiaryScreen.tsx
This PR fixes [IPCT1-418] at https://impactmarket.atlassian.net/browse/IPCT1-418
- Manually
- Automated
> [IPCT1-418] prevent unknown if funds run out

- .eslintrc.js
- config.ts
- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/assets/languages.json
- src/components/ShimmerPlaceholder.tsx
- src/components/community/Description.tsx
- src/components/community/__mocks__/Description.tsx
- src/helpers/index.ts
- src/views/community/details/__tests__/__snapshots__/index.spec.tsx.snap
- src/views/community/details/__tests__/index.spec.tsx
- src/views/community/details/index.tsx
- src/views/community/extendedDetails/__tests__/__snapshots__/snapshots.spec.tsx.snap
- src/views/community/extendedDetails/__tests__/snapshots.spec.tsx
- src/views/community/extendedDetails/index.tsx
This PR fixes [IPCT1-292] at https://impactmarket.atlassian.net/browse/IPCT1-292
- Manually
- Automated
> [IPCT1-292] community description translation

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/components/Modal.tsx
- src/helpers/constants.ts
- src/helpers/redux/actions/auth.ts
- src/helpers/types/endpoints.ts
- src/helpers/types/redux.ts
- src/helpers/types/state.ts
- src/navigator/StackNavigator.tsx
- src/navigator/TabNavigator.tsx
- src/navigator/header/CreateCommunity.tsx
- src/views/communities/index.tsx
- src/views/community/beneficiary/AnonymousReportScreen.tsx
- src/views/profile/auth/index.tsx
- src/views/welcome/index.tsx
> fix anonymous report

- src/components/Modal.tsx
- src/helpers/redux/actions/auth.ts
- src/helpers/types/endpoints.ts
- src/helpers/types/redux.ts
- src/helpers/types/state.ts
- src/views/profile/auth/index.tsx
> update returned errors

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/services/api/base.ts
- src/services/api/routes/story.ts
- src/views/community/details/__tests__/__snapshots__/index.spec.tsx.snap
- src/views/community/details/index.tsx
- src/views/stories/NewStory.tsx
> fix create stories

- src/services/api/base.ts
- src/services/api/routes/community.ts
- src/services/api/routes/story.ts
- src/services/api/routes/user.ts
- src/views/createEditCommunity/__tests__/create.test.tsx
- src/views/createEditCommunity/create.tsx
- src/views/createEditCommunity/edit.tsx
- src/views/createEditCommunity/metadata.tsx
- src/views/profile/index.tsx
> fix image uploading + edit community

- src/views/createEditCommunity/create.tsx
> fix profile + useeffect conditions

- src/assets/i18n/en.ts
- src/assets/i18n/pt.ts
- src/helpers/index.ts
- src/views/communities/List.tsx
- src/views/profile/auth/index.tsx
> recover inactive account

- src/helpers/redux/actions/stories.ts
- src/helpers/redux/sagas/stories.ts
- src/helpers/types/redux.ts
- src/services/api/routes/story.ts
- src/views/communities/MyStoriesCard.tsx
- src/views/communities/Stories.tsx
- src/views/stories/Carousel.tsx
> fix loading my stories

- App.tsx
- src/config/api.ts
- src/services/api/base.ts
- src/services/api/routes/community.ts
- src/services/api/routes/story.ts
- src/services/api/routes/system.ts
- src/services/api/routes/user.ts
This PR fixes [IPCT1-450] at https://impactmarket.atlassian.net/browse/IPCT1-450
- Manually
- Automated
> [IPCT1-450] new base

- App.tsx
- src/config/api.ts
- src/services/api/base.ts
- src/services/api/index.ts
- src/services/api/routes/community.ts
- src/services/api/routes/story.ts
- src/services/api/routes/system.ts
- src/services/api/routes/user.ts
- src/views/community/manager/views/AddManagerScreen.tsx
- src/views/stories/Carousel.tsx
This PR fixes [IPCT1-451] at https://impactmarket.atlassian.net/browse/IPCT1-451
- Manually
- Automated
> [IPCT1-451] non static

- jestSetup.ts
- src/components/svg/header/BackSvg.tsx
- src/views/createEditCommunity/__tests__/__snapshots__/snapshots.spec.tsx.snap
- src/views/createEditCommunity/__tests__/create.test.tsx
- src/views/createEditCommunity/create.tsx
This PR fixes [IPCT1-495] at https://impactmarket.atlassian.net/browse/IPCT1-495
- Manually
- Automated
https://drive.google.com/file/d/13p57m0-gkbyN0HLTyldpmxYf7pakIZKK/view?usp=sharing
> [IPCT1-495] fix load past community form

- jestSetup.ts
- package.json
- src/views/createEditCommunity/__tests__/__snapshots__/snapshots.spec.tsx.snap
- src/views/createEditCommunity/create.tsx
- yarn.lock
This PR fixes [IPCT1-438] at https://impactmarket.atlassian.net/browse/IPCT1-438
- Manually
- Automated
> [IPCT1-438] add KeyboardAwareScrollView

- src/helpers/index.ts
This PR fixes [IPCT1-499] at https://impactmarket.atlassian.net/browse/IPCT1-499
- Manually
- Automated
> [IPCT1-499] fix loading profile on open app

- src/components/svg/header/FaqSvg.tsx
- src/views/communities/List.tsx
- src/views/communities/Stories.tsx
- src/views/communities/communities/index.tsx
- src/views/communities/index.tsx
- src/views/community/manager/index.tsx
- src/views/createEditCommunity/__tests__/create.test.tsx
- src/views/createEditCommunity/contract.tsx
- src/views/createEditCommunity/create.tsx
- src/views/profile/auth/index.tsx
- src/views/stories/NewStory.tsx
> minimal home UI updates
